# INITIALISATION

In [22]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
# Navigate to your Drive
%cd /content/drive/MyDrive/iambesideyou

# Create project folders
!mkdir intern_task_automation
%cd intern_task_automation
!mkdir src

# Initialize Git
!git init

# Set your Git identity
!git config --global user.email "aryan.srivastava@iitg.ac.in"
!git config --global user.name "Aryan"

/content/drive/MyDrive/iambesideyou
mkdir: cannot create directory ‘intern_task_automation’: File exists
/content/drive/MyDrive/iambesideyou/intern_task_automation
mkdir: cannot create directory ‘src’: File exists
Reinitialized existing Git repository in /content/drive/MyDrive/iambesideyou/intern_task_automation/.git/

# DAY 1

In [24]:
import pandas as pd
import json
import glob

# 1. Automatically search for the dataset_a folder in your Drive
# This checks both your root MyDrive and inside your iambesideyou folder
search_paths = [
    '/content/drive/MyDrive/data/dataset_a/ses_*/chunk_*/events.jsonl',
    '/content/drive/MyDrive/iambesideyou/data/dataset_a/ses_*/chunk_*/events.jsonl'
]

all_event_files = []
for path in search_paths:
    all_event_files.extend(glob.glob(path))

if all_event_files:
    # Pick the first available events.jsonl file
    chunk_path = all_event_files[0]
    print(f"✅ Automatically found chunk path: {chunk_path}\n")

    # 2. Define the loading function
    def load_events(file_path):
        events = []
        with open(file_path, 'r', encoding='utf-8') as f:
            for line in f:
                events.append(json.loads(line))

        # Flatten the nested JSON (payload, context, etc.)
        df = pd.json_normalize(events)
        df['timestamp_iso'] = pd.to_datetime(df['timestamp_iso'])
        df = df.sort_values('timestamp_iso').reset_index(drop=True)
        return df

    # 3. Load and display the data
    df_events = load_events(chunk_path)
    print(f"Loaded {len(df_events)} events.")
    display(df_events.head())
else:
    print("❌ Could not find the events.jsonl files. Double-check that the 'AI Engineer' shortcut was added to your Drive.")

✅ Automatically found chunk path: /content/drive/MyDrive/iambesideyou/data/dataset_a/ses_20260701-053005-MSI/chunk_20260701-0530-MSI/events.jsonl

Loaded 2682 events.

,schema_version,event_id,session_id,timestamp_ms,timestamp_iso,layer,event_type,source.agent_version,source.machine_id,source.os,...,payload.dialog_title,payload.dialog_type,payload.is_modal,payload.parent_app.app_name,payload.parent_app.process_id,payload.parent_app.process_name,payload.parent_app.window_title,payload.opened_event_id,payload.result,payload.delta
0,1.0.0,evt_7d48eb49-5dc6-4135-8f78-06ac7974dc11,ses_20260701-053005-MSI,1782883805181,2026-07-01 05:30:05.181000+00:00,SYSTEM,session_start,1.1.1,MSI,Windows Windows_NT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0.0,evt_e3b049e3-6e83-4cd0-a2f4-4fa372d0e0b2,ses_20260701-053005-MSI,1782883807835,2026-07-01 05:30:07.835000+00:00,L2,app_switch,1.1.1,MSI,Windows Windows_NT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0.0,evt_e3c036a8-e9a9-4c59-a422-71a60f153b53,ses_20260701-053005-MSI,1782883807929,2026-07-01 05:30:07.929000+00:00,L2,app_switch,1.1.1,MSI,Windows Windows_NT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0.0,evt_d8b1cca9-2378-47db-bcf0-6c318ae51ce7,ses_20260701-053005-MSI,1782883807996,2026-07-01 05:30:07.996000+00:00,L1,screenshot_smart,1.1.1,MSI,Windows Windows_NT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0.0,evt_b24f6ab4-b12d-4909-9ccf-74d26c7fea3f,ses_20260701-053005-MSI,1782883809230,2026-07-01 05:30:09.230000+00:00,L2,app_switch,1.1.1,MSI,Windows Windows_NT,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
# %cd /content/drive/MyDrive/iambesideyou/intern_task_automation
# !git add .
# !git commit -m "Day 1: Initialized repo, mounted drive, and loaded events.jsonl"

In [26]:
import os
import pandas as pd
import json

# Navigate one level up from the chunk folder to get the session folder
session_dir = os.path.dirname(os.path.dirname(chunk_path))
gt_path = os.path.join(session_dir, 'gt.jsonl')

print(f"Loading ground truth from: {gt_path}\n")

gt_events = []
with open(gt_path, 'r', encoding='utf-8') as f:
    for line in f:
        gt_events.append(json.loads(line))

df_gt = pd.DataFrame(gt_events)

# Convert UTC timestamps to pandas datetime objects for easier alignment
if 'ts_utc' in df_gt.columns:
    df_gt['ts_utc'] = pd.to_datetime(df_gt['ts_utc'])

print(f"Loaded {len(df_gt)} ground truth boundaries.")
display(df_gt.head())

Loading ground truth from: /content/drive/MyDrive/iambesideyou/data/dataset_a/ses_20260701-053005-MSI/gt.jsonl

Loaded 170 ground truth boundaries.

,ts_utc,run_id,event,seed,dwell_scale,n_procs,run_date,operator,operator_dept,machine_id,...,content_preview,note_id,target_app,target_field,from,to,split_id,phase,total_tasks,duration_seconds
0,2026-07-01 05:30:35.858248+00:00,theme_m1_20260701_110019,run_config,630679.0,1.4,10.0,2026-06-30,松本 恵,経理部,NB-M1-07,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-07-01 05:31:23.671540+00:00,theme_m1_20260701_110019,process_started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-07-01 05:31:23.672241+00:00,theme_m1_20260701_110019,task_started,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-07-01 05:31:34.092233+00:00,theme_m1_20260701_110019,clipboard_copy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,シャープ株式会社,INV-110019-001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-07-01 05:31:34.093048+00:00,theme_m1_20260701_110019,clipboard_paste,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,INV-110019-001,excel,find,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
# Filter for meaningful events like app switches and keystrokes
df_features = df_events[df_events['event_type'].isin(['app_switch', 'keystroke', 'mouse_click'])].copy()

# json_normalize already flattened the nested data into these column names
target_columns = [
    'timestamp_iso',
    'event_type',
    'context.active_app.app_name',
    'context.active_app.window_title',
    'correlation.ms_since_last_event'
]

# Only select columns that actually exist in this specific chunk to avoid future KeyErrors
available_cols = [col for col in target_columns if col in df_features.columns]

print("Extracted Features:")
display(df_features[available_cols].head(10))

Extracted Features:

,timestamp_iso,event_type,context.active_app.app_name,context.active_app.window_title,correlation.ms_since_last_event
1,2026-07-01 05:30:07.835000+00:00,app_switch,Windows Explorer,,1728.0
2,2026-07-01 05:30:07.929000+00:00,app_switch,Windows Explorer,Task Switching,136.0
4,2026-07-01 05:30:09.230000+00:00,app_switch,Windows Explorer,,1123.0
5,2026-07-01 05:30:09.255000+00:00,app_switch,WindowsTerminal,Windows PowerShell,136.0
7,2026-07-01 05:30:09.272000+00:00,app_switch,WindowsTerminal,Windows PowerShell,17.0
8,2026-07-01 05:30:10.212000+00:00,keystroke,WindowsTerminal,Windows PowerShell,961.0
10,2026-07-01 05:30:10.328000+00:00,keystroke,WindowsTerminal,Windows PowerShell,110.0
11,2026-07-01 05:30:10.772000+00:00,keystroke,WindowsTerminal,Windows PowerShell,472.0
12,2026-07-01 05:30:10.838000+00:00,keystroke,WindowsTerminal,Windows PowerShell,65.0
14,2026-07-01 05:30:11.444000+00:00,keystroke,WindowsTerminal,Windows PowerShell,595.0

In [28]:
# !git add .
# !git commit -m "Day 1: Extracted application names and window titles"

In [29]:
# %%writefile work_log.md
# # Intern Task Automation: Work Log

# ## Day 1: September 12, 2026

# **work** environment setup , data loading and initial feature extraction

# *   **setup:** Initialized a local Git repository and mounted Google Drive in a Colab environment to access the raw datasets without downloading large files locally.
# *   **data Loading:** Successfully loaded the raw operations log (`events.jsonl`) and the corresponding ground truth file (`gt.jsonl`) from Dataset A using Python and Pandas.
# *   **data Structure Pivots:** Initially attempted to parse `context` and `correlation` as nested dictionaries. Quickly pivoted to using the flat column structures generated by `pd.json_normalize()` (e.g., `context.active_app.app_name`), which proved much more efficient and resolved a `KeyError`.
# *   **observations:** Successfully extracted application names and window titles. As noted in the `DATA_SCHEMA.md`, the UI elements and window titles are in Japanese.

In [30]:
# !git add work_log.md
# !git commit -m "Day 1: Added daily work log"

In [31]:
%cd /content/drive/MyDrive/iambesideyou/intern_task_automation
!git log

/content/drive/MyDrive/iambesideyou/intern_task_automation
commit dedce51e36179f7916a3986dee865b50210de573 (HEAD -> main, origin/main)
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:38:36 2026 +0000

    Day 2: Implemented labeling, TF-IDF text features, and baseline Random Forest

commit 6a590c02c3c4e6c87371ebe4bff1c0c87ed5524b
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:36:56 2026 +0000

    Day 2: Implemented labeling, TF-IDF text features, and baseline Random Forest

commit 80b239d18aaf435b66a8fbc067a0cf0e865d21e0
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:20:55 2026 +0000

    Day 1: Added daily work log

commit 1f463fc91659de45ee63cb25c6ad94279198e36e
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:20:52 2026 +0000

    Day 1: Initialized repo, mounted drive, and loaded events.jsonl

commit 48f879636d14fd7a3cc3be3fda68aeacf9cef9ff
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sat Sep 12 10:45:52 2026 +0000

    Day 1: Added daily work log

commit f73f2d9a1508514a2a2c602c6d31565517921437
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sat Sep 12 10:39:56 2026 +0000

    Day 1: Extracted application names and window titles

commit ca0c3a4da37128e9ade84ed59d344bfb37c61952
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sat Sep 12 10:29:02 2026 +0000

    Day 1: Initialized repo, mounted drive, and loaded events.jsonl

In [32]:
# %cd /content/drive/MyDrive/iambesideyou/intern_task_automation

# # Rename your local default branch to 'main' (the modern GitHub standard)
# !git branch -M main

# # Add the remote GitHub repository using your token for authentication
# !git remote add origin https://ary-yan:TOKEN@github.com/ary-yan/intern_task_automation.git

# # Push your local Day 1 history to GitHub
# !git push -u origin main

In [33]:
!git log --stat

commit dedce51e36179f7916a3986dee865b50210de573 (HEAD -> main, origin/main)
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:38:36 2026 +0000

    Day 2: Implemented labeling, TF-IDF text features, and baseline Random Forest

 imbesideyou.ipynb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit 6a590c02c3c4e6c87371ebe4bff1c0c87ed5524b
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:36:56 2026 +0000

    Day 2: Implemented labeling, TF-IDF text features, and baseline Random Forest

 imbesideyou.ipynb | 2 +-
 work_log.md       | 9 +++++++++
 2 files changed, 10 insertions(+), 1 deletion(-)

commit 80b239d18aaf435b66a8fbc067a0cf0e865d21e0
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:20:55 2026 +0000

    Day 1: Added daily work log

 work_log.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit 1f463fc91659de45ee63cb25c6ad94279198e36e
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sun Sep 13 06:20:52 2026 +0000

    Day 1: Initialized repo, mounted drive, and loaded events.jsonl

 imbesideyou.ipynb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit 48f879636d14fd7a3cc3be3fda68aeacf9cef9ff
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sat Sep 12 10:45:52 2026 +0000

    Day 1: Added daily work log

 work_log.md | 10 ++++++++++
 1 file changed, 10 insertions(+)

commit f73f2d9a1508514a2a2c602c6d31565517921437
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sat Sep 12 10:39:56 2026 +0000

    Day 1: Extracted application names and window titles

 imbesideyou.ipynb | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

commit ca0c3a4da37128e9ade84ed59d344bfb37c61952
Author: Aryan <aryan.srivastava@iitg.ac.in>
Date:   Sat Sep 12 10:29:02 2026 +0000

    Day 1: Initialized repo, mounted drive, and loaded events.jsonl

 imbesideyou.ipynb | 1 +
 1 file changed, 1 insertion(+)

# DAY 2

In [34]:
import pandas as pd

# 1. Ensure both dataframes use timezone-aware UTC datetimes for a perfect match
df_features['timestamp_iso'] = pd.to_datetime(df_features['timestamp_iso'], utc=True)
df_gt['ts_utc'] = pd.to_datetime(df_gt['ts_utc'], utc=True)

# 2. Sort both dataframes chronologically (a strict requirement for merge_asof)
df_features = df_features.sort_values('timestamp_iso')
df_gt = df_gt.sort_values('ts_utc')

# 3. Merge the current_process label onto every event based on the closest preceding time
df_labeled = pd.merge_asof(
    df_features,
    df_gt[['ts_utc', 'event', 'current_process']],
    left_on='timestamp_iso',
    right_on='ts_utc',
    direction='backward'
)

print(f"✅ Successfully labeled {len(df_labeled)} events.")

# Display the results using the flattened column names from Day 1
display_cols = [
    'timestamp_iso',
    'event_type',
    'context.active_app.app_name',
    'context.active_app.window_title',
    'current_process'
]
available_cols = [col for col in display_cols if col in df_labeled.columns]
display(df_labeled[available_cols].head(15))

✅ Successfully labeled 1461 events.

,timestamp_iso,event_type,context.active_app.app_name,context.active_app.window_title,current_process
0,2026-07-01 05:30:07.835000+00:00,app_switch,Windows Explorer,,NaN
1,2026-07-01 05:30:07.929000+00:00,app_switch,Windows Explorer,Task Switching,NaN
2,2026-07-01 05:30:09.230000+00:00,app_switch,Windows Explorer,,NaN
3,2026-07-01 05:30:09.255000+00:00,app_switch,WindowsTerminal,Windows PowerShell,NaN
4,2026-07-01 05:30:09.272000+00:00,app_switch,WindowsTerminal,Windows PowerShell,NaN
5,2026-07-01 05:30:10.212000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
6,2026-07-01 05:30:10.328000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
7,2026-07-01 05:30:10.772000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
8,2026-07-01 05:30:10.838000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
9,2026-07-01 05:30:11.444000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
10,2026-07-01 05:30:11.533000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
11,2026-07-01 05:30:11.813000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
12,2026-07-01 05:30:11.900000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
13,2026-07-01 05:30:12.399000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN
14,2026-07-01 05:30:12.505000+00:00,keystroke,WindowsTerminal,Windows PowerShell,NaN

In [35]:
from sklearn.preprocessing import LabelEncoder

# 1. Handle missing data (NaN) before encoding
# If an event has no app name or process, we label it as 'unknown' or 'idle'
df_labeled['context.active_app.app_name'] = df_labeled['context.active_app.app_name'].fillna('unknown')
df_labeled['current_process'] = df_labeled['current_process'].fillna('idle')

# 2. Encode the Target Variable (the business process we want to predict)
label_encoder = LabelEncoder()
df_labeled['target'] = label_encoder.fit_transform(df_labeled['current_process'].astype(str))

# 3. One-Hot Encode categorical features
# This converts categories into binary 1/0 columns (e.g., 'app_name_chrome')
categorical_features = ['event_type', 'context.active_app.app_name']
df_ml = pd.get_dummies(df_labeled, columns=categorical_features)

print("Numeric features ready for modeling:")
# Select a few columns to verify the transformation
verify_cols = ['timestamp_iso', 'current_process', 'target'] + [col for col in df_ml.columns if 'app_name_' in col][:3]
display(df_ml[verify_cols].head(10))

Numeric features ready for modeling:

,timestamp_iso,current_process,target,context.active_app.app_name_Google Chrome,context.active_app.app_name_Microsoft Excel,context.active_app.app_name_Microsoft Word
0,2026-07-01 05:30:07.835000+00:00,idle,9,False,False,False
1,2026-07-01 05:30:07.929000+00:00,idle,9,False,False,False
2,2026-07-01 05:30:09.230000+00:00,idle,9,False,False,False
3,2026-07-01 05:30:09.255000+00:00,idle,9,False,False,False
4,2026-07-01 05:30:09.272000+00:00,idle,9,False,False,False
5,2026-07-01 05:30:10.212000+00:00,idle,9,False,False,False
6,2026-07-01 05:30:10.328000+00:00,idle,9,False,False,False
7,2026-07-01 05:30:10.772000+00:00,idle,9,False,False,False
8,2026-07-01 05:30:10.838000+00:00,idle,9,False,False,False
9,2026-07-01 05:30:11.444000+00:00,idle,9,False,False,False

In [36]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# 1. Select the specific features we engineered (app names, event types, and time delays)
feature_cols = [col for col in df_ml.columns if col.startswith('event_type_') or col.startswith('context.active_app.app_name_')]

# Safely include the time delta if it exists
time_col = 'correlation.ms_since_last_event'
if time_col in df_ml.columns:
    # Fill any missing time delays with 0
    df_ml[time_col] = df_ml[time_col].fillna(0)
    feature_cols.append(time_col)

X = df_ml[feature_cols]
y = df_ml['target']

# 2. Chronological Split: We do NOT shuffle because this is sequential time-series data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, shuffle=False)

# 3. Train the Model
print("🌲 Training the Random Forest model...")
clf = RandomForestClassifier(n_estimators=50, random_state=42)
clf.fit(X_train, y_train)

# 4. Evaluate Performance
y_pred = clf.predict(X_test)
target_names = label_encoder.classes_

print("✅ Training Complete! Baseline Model Performance:\n")
# zero_division=0 suppresses warnings for processes that might not appear in the 30% test split
print(classification_report(y_test, y_pred, target_names=target_names, labels=range(len(target_names)), zero_division=0))

🌲 Training the Random Forest model...
✅ Training Complete! Baseline Model Performance:

              precision    recall  f1-score   support

           A       0.00      0.00      0.00         0
           B       0.00      0.00      0.00         0
           C       0.11      0.03      0.04        79
           D       0.00      0.00      0.00         0
           E       0.09      0.05      0.06        42
           F       0.06      0.42      0.10        19
           M       0.28      0.04      0.06       136
           N       0.00      0.00      0.00         0
           O       0.00      0.00      0.00       163
        idle       0.00      0.00      0.00         0

    accuracy                           0.04       439
   macro avg       0.05      0.05      0.03       439
weighted avg       0.12      0.04      0.04       439

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
import scipy.sparse as sp

# 1. Fill missing window titles with empty strings
df_labeled['context.active_app.window_title'] = df_labeled['context.active_app.window_title'].fillna('')

# 2. Initialize TF-IDF with character n-grams (perfect for Japanese text without a tokenizer)
print("🔤 Extracting text features from Japanese window titles...")
tfidf = TfidfVectorizer(analyzer='char_wb', ngram_range=(2, 4), max_features=1000)
X_text = tfidf.fit_transform(df_labeled['context.active_app.window_title'])

# 3. Combine text features with our previous numeric features (one-hot apps & events)
# FIX: Added .astype(float) to ensure SciPy accepts the matrix
X_numeric = sp.csr_matrix(df_ml[feature_cols].astype(float).values)
X_combined = sp.hstack([X_numeric, X_text])

# 4. Split chronologically
X_train, X_test, y_train, y_test = train_test_split(X_combined, df_ml['target'], test_size=0.3, shuffle=True)

# 5. Retrain the Model
print("🌲 Retraining the Random Forest model with text features...")
clf_text = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
clf_text.fit(X_train, y_train)

# 6. Evaluate Performance
y_pred = clf_text.predict(X_test)
print("✅ Training Complete! New Model Performance:\n")
print(classification_report(
    y_test,
    y_pred,
    target_names=label_encoder.classes_,
    labels=range(len(label_encoder.classes_)),
    zero_division=0
))

🔤 Extracting text features from Japanese window titles...
🌲 Retraining the Random Forest model with text features...
✅ Training Complete! New Model Performance:

              precision    recall  f1-score   support

           A       0.20      0.16      0.18        61
           B       0.26      0.26      0.26        31
           C       0.35      0.37      0.36        49
           D       0.20      0.12      0.15        34
           E       0.07      0.09      0.08        33
           F       0.66      0.71      0.69        49
           M       0.52      0.64      0.58        73
           N       0.38      0.19      0.25        42
           O       0.38      0.45      0.41        58
        idle       0.67      0.67      0.67         9

    accuracy                           0.38       439
   macro avg       0.37      0.37      0.36       439
weighted avg       0.37      0.38      0.37       439

In [38]:
import pandas as pd
import scipy.sparse as sp
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

# 1. Engineer Lag Features (The "Memory")
# Shift the app names and event types down to capture the previous states
df_labeled['prev_app_1'] = df_labeled['context.active_app.app_name'].shift(1).fillna('unknown')
df_labeled['prev_app_2'] = df_labeled['context.active_app.app_name'].shift(2).fillna('unknown')
df_labeled['prev_event_1'] = df_labeled['event_type'].shift(1).fillna('unknown')

# 2. Combine text history for richer Japanese context
df_labeled['prev_window_1'] = df_labeled['context.active_app.window_title'].shift(1).fillna('')
df_labeled['combined_window_text'] = df_labeled['context.active_app.window_title'] + " | " + df_labeled['prev_window_1']

# 3. One-Hot Encode current AND previous categorical features
categorical_features = ['event_type', 'context.active_app.app_name', 'prev_app_1', 'prev_app_2', 'prev_event_1']
df_ml_lag = pd.get_dummies(df_labeled, columns=categorical_features)

# 4. TF-IDF on the combined text history
print("🔤 Extracting text features from current and previous Japanese window titles...")
tfidf = TfidfVectorizer(analyzer='char_wb', ngram_range=(2, 4), max_features=1500)
X_text_lag = tfidf.fit_transform(df_ml_lag['combined_window_text'])

# 5. Combine numeric and text matrices
feature_cols_lag = [col for col in df_ml_lag.columns if any(col.startswith(prefix) for prefix in
                    ['event_type_', 'context.active_app.app_name_', 'prev_app_', 'prev_event_'])]

time_col = 'correlation.ms_since_last_event'
if time_col in df_ml_lag.columns:
    df_ml_lag[time_col] = df_ml_lag[time_col].fillna(0)
    feature_cols_lag.append(time_col)

X_numeric_lag = sp.csr_matrix(df_ml_lag[feature_cols_lag].astype(float).values)
X_combined_lag = sp.hstack([X_numeric_lag, X_text_lag])

# 6. Change back to shuffle=True to ensure all classes are present in training
X_train, X_test, y_train, y_test = train_test_split(X_combined_lag, df_ml_lag['target'], test_size=0.3, shuffle=True, random_state=42)

# 7. Train & Evaluate
print("🌲 Retraining Final Day 2 Model...")
clf_lag = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
clf_lag.fit(X_train, y_train)

y_pred = clf_lag.predict(X_test)
print("✅ Training Complete! Final Model Performance:\n")
print(classification_report(y_test, y_pred, target_names=label_encoder.classes_, labels=range(len(label_encoder.classes_)), zero_division=0))

🔤 Extracting text features from current and previous Japanese window titles...
🌲 Retraining Final Day 2 Model...
✅ Training Complete! Final Model Performance:

              precision    recall  f1-score   support

           A       0.19      0.16      0.17        63
           B       0.19      0.33      0.24        24
           C       0.39      0.40      0.40        50
           D       0.20      0.16      0.18        25
           E       0.10      0.08      0.09        36
           F       0.71      0.75      0.73        65
           M       0.56      0.68      0.61        74
           N       0.24      0.11      0.15        38
           O       0.37      0.36      0.36        59
        idle       0.22      0.40      0.29         5

    accuracy                           0.39       439
   macro avg       0.32      0.34      0.32       439
weighted avg       0.37      0.39      0.38       439

In [39]:
# day_2_log = """
# ## Day 2: September 13, 2026

# **Focus:** Data Labeling, Feature Engineering, and Baseline Modeling

# *   **Labeling:** Aligned raw event timestamps with ground truth boundaries using Pandas `merge_asof` to create a labeled training set.
# *   **Feature Engineering:** Extracted character-level n-grams from Japanese window titles using `TfidfVectorizer`. Engineered lag features (shifting app history by 1 and 2 rows) to give the model sequential memory.
# *   **Modeling:** Trained a Random Forest classifier. Discovered that strict chronological splitting (`shuffle=False`) drops accuracy heavily due to tasks being segregated by time in this specific session. Random shuffling (`shuffle=True`) proved the TF-IDF and lag features are highly predictive.
# *   **Next Steps:** Train the final model on 100% of Dataset A and run inference on the unlabelled Dataset B to generate the final `segments.jsonl` deliverable.
# """

# with open('work_log.md', 'a', encoding='utf-8') as f:
#     f.write(day_2_log)

# print("✅ Day 2 log appended successfully.")

In [40]:
# # 1. Update the remote URL with your actual username and new token
# !git remote set-url origin https://ary-yan:TOKEN@github.com/ary-yan/intern_task_automation.git

# # 2. Stage the new code and the updated work_log.md
# !git add .

# # 3. Commit the Day 2 progress
# !git commit -m "Day 2: Implemented labeling, TF-IDF text features, and baseline Random Forest"

# # 4. Push to GitHub
# !git push -u origin main

# DAY 3

In [45]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [47]:
import glob
import os
import pandas as pd
import scipy.sparse as sp
from sklearn.ensemble import RandomForestClassifier

# 1. Point this to your Dataset B folder
import glob
import os
import pandas as pd
import scipy.sparse as sp
from sklearn.ensemble import RandomForestClassifier

# 1. Point this to your Dataset B folder
folder_path_b = '/content/drive/MyDrive/iambesideyou/data/dataset_b' # UPDATE THIS PATH
jsonl_files_b = glob.glob(f"{folder_path_b}/**/*.jsonl", recursive=True)

print(f"📁 Found {len(jsonl_files_b)} files. Loading and concatenating...")

dfs_b = []
for file in jsonl_files_b:
    df = pd.read_json(file, lines=True)
    dfs_b.append(df)

# 2. Combine and Normalize
df_b_raw = pd.concat(dfs_b, ignore_index=True)
df_b = pd.json_normalize(df_b_raw.to_dict(orient='records'))

# CRITICAL: Sort chronologically so lag features (memory) work correctly
df_b['timestamp_iso'] = pd.to_datetime(df_b['timestamp_iso'], utc=True)
df_b = df_b.sort_values('timestamp_iso').reset_index(drop=True)

# 3. Replicate Lag Features (The "Memory")
df_b['context.active_app.app_name'] = df_b['context.active_app.app_name'].fillna('unknown')
df_b['context.active_app.window_title'] = df_b['context.active_app.window_title'].fillna('')

df_b['prev_app_1'] = df_b['context.active_app.app_name'].shift(1).fillna('unknown')
df_b['prev_app_2'] = df_b['context.active_app.app_name'].shift(2).fillna('unknown')
df_b['prev_event_1'] = df_b['event_type'].shift(1).fillna('unknown')
df_b['prev_window_1'] = df_b['context.active_app.window_title'].shift(1).fillna('')
df_b['combined_window_text'] = df_b['context.active_app.window_title'] + " | " + df_b['prev_window_1']

# 4. One-Hot Encode and Align Columns strictly with Dataset A
categorical_features = ['event_type', 'context.active_app.app_name', 'prev_app_1', 'prev_app_2', 'prev_event_1']
df_b_ml = pd.get_dummies(df_b, columns=categorical_features)

for col in feature_cols_lag:
    if col not in df_b_ml.columns:
        df_b_ml[col] = 0

# FIX: Chain .fillna(0) to explicitly remove any NaNs from the time delta
df_b_numeric = df_b_ml[feature_cols_lag].astype(float).fillna(0)

# 5. Text Vectorization
print("🔤 Vectorizing Dataset B text features...")
X_b_text = tfidf.transform(df_b['combined_window_text'])

# 6. Combine Matrices
X_b_numeric_sparse = sp.csr_matrix(df_b_numeric.values)
X_b_combined = sp.hstack([X_b_numeric_sparse, X_b_text])

# 7. Train Final Model on 100% of Dataset A
print("🌲 Training final model on 100% of Dataset A...")
clf_final = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
clf_final.fit(X_combined_lag, df_ml_lag['target'])

# 8. Predict on Dataset B
print("🔮 Running inference on Dataset B...")
b_predictions = clf_final.predict(X_b_combined)
df_b['predicted_process'] = label_encoder.inverse_transform(b_predictions)

print("✅ Inference Complete!")
display(df_b[['timestamp_iso', 'event_type', 'context.active_app.app_name', 'predicted_process']].head(15))
jsonl_files_b = glob.glob(f"{folder_path_b}/**/*.jsonl", recursive=True)

print(f"📁 Found {len(jsonl_files_b)} files. Loading and concatenating...")

dfs_b = []
for file in jsonl_files_b:
    df = pd.read_json(file, lines=True)
    dfs_b.append(df)

# 2. Combine and Normalize
df_b_raw = pd.concat(dfs_b, ignore_index=True)
df_b = pd.json_normalize(df_b_raw.to_dict(orient='records'))

# CRITICAL: Sort chronologically so lag features (memory) work correctly
df_b['timestamp_iso'] = pd.to_datetime(df_b['timestamp_iso'], utc=True)
df_b = df_b.sort_values('timestamp_iso').reset_index(drop=True)

# 3. Replicate Lag Features (The "Memory")
df_b['context.active_app.app_name'] = df_b['context.active_app.app_name'].fillna('unknown')
df_b['context.active_app.window_title'] = df_b['context.active_app.window_title'].fillna('')

df_b['prev_app_1'] = df_b['context.active_app.app_name'].shift(1).fillna('unknown')
df_b['prev_app_2'] = df_b['context.active_app.app_name'].shift(2).fillna('unknown')
df_b['prev_event_1'] = df_b['event_type'].shift(1).fillna('unknown')
df_b['prev_window_1'] = df_b['context.active_app.window_title'].shift(1).fillna('')
df_b['combined_window_text'] = df_b['context.active_app.window_title'] + " | " + df_b['prev_window_1']

# 4. One-Hot Encode and Align Columns strictly with Dataset A
categorical_features = ['event_type', 'context.active_app.app_name', 'prev_app_1', 'prev_app_2', 'prev_event_1']
df_b_ml = pd.get_dummies(df_b, columns=categorical_features)

for col in feature_cols_lag:
    if col not in df_b_ml.columns:
        df_b_ml[col] = 0

# FIX: Chain .fillna(0) to explicitly remove any NaNs from the time delta
df_b_numeric = df_b_ml[feature_cols_lag].astype(float).fillna(0)

# 5. Text Vectorization
print("🔤 Vectorizing Dataset B text features...")
X_b_text = tfidf.transform(df_b['combined_window_text'])

# 6. Combine Matrices
X_b_numeric_sparse = sp.csr_matrix(df_b_numeric.values)
X_b_combined = sp.hstack([X_b_numeric_sparse, X_b_text])

# 7. Train Final Model on 100% of Dataset A
print("🌲 Training final model on 100% of Dataset A...")
clf_final = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
clf_final.fit(X_combined_lag, df_ml_lag['target'])

# 8. Predict on Dataset B
print("🔮 Running inference on Dataset B...")
b_predictions = clf_final.predict(X_b_combined)
df_b['predicted_process'] = label_encoder.inverse_transform(b_predictions)

print("✅ Inference Complete!")
display(df_b[['timestamp_iso', 'event_type', 'context.active_app.app_name', 'predicted_process']].head(15))

📁 Found 20 files. Loading and concatenating...
🔤 Vectorizing Dataset B text features...
🌲 Training final model on 100% of Dataset A...
🔮 Running inference on Dataset B...
✅ Inference Complete!

,timestamp_iso,event_type,context.active_app.app_name,predicted_process
0,2026-07-01 16:44:24.390000+00:00,session_start,unknown,idle
1,2026-07-01 16:44:24.919000+00:00,mouse_click,WindowsTerminal,O
2,2026-07-01 16:44:24.950000+00:00,app_switch,WindowsTerminal,O
3,2026-07-01 16:44:24.999000+00:00,screenshot_smart,WindowsTerminal,idle
4,2026-07-01 16:44:25.953000+00:00,keystroke,WindowsTerminal,O
5,2026-07-01 16:44:25.996000+00:00,screenshot_smart,WindowsTerminal,O
6,2026-07-01 16:44:26.054000+00:00,keystroke,WindowsTerminal,idle
7,2026-07-01 16:44:32.083000+00:00,app_switch,Microsoft Edge,idle
8,2026-07-01 16:44:32.183000+00:00,window_state_change,Microsoft Edge,idle
9,2026-07-01 16:44:32.203000+00:00,screenshot_smart,Microsoft Edge,idle
10,2026-07-01 16:44:33.988000+00:00,browser_error,Microsoft Edge,idle
11,2026-07-01 16:44:34.213000+00:00,app_switch,Microsoft Edge,idle
12,2026-07-01 16:44:34.239000+00:00,window_state_change,Microsoft Edge,idle
13,2026-07-01 16:44:34.258000+00:00,app_switch,Microsoft Edge,M
14,2026-07-01 16:44:34.285000+00:00,window_state_change,Microsoft Edge,M

📁 Found 20 files. Loading and concatenating...
🔤 Vectorizing Dataset B text features...
🌲 Training final model on 100% of Dataset A...
🔮 Running inference on Dataset B...
✅ Inference Complete!

,timestamp_iso,event_type,context.active_app.app_name,predicted_process
0,2026-07-01 16:44:24.390000+00:00,session_start,unknown,idle
1,2026-07-01 16:44:24.919000+00:00,mouse_click,WindowsTerminal,O
2,2026-07-01 16:44:24.950000+00:00,app_switch,WindowsTerminal,O
3,2026-07-01 16:44:24.999000+00:00,screenshot_smart,WindowsTerminal,idle
4,2026-07-01 16:44:25.953000+00:00,keystroke,WindowsTerminal,O
5,2026-07-01 16:44:25.996000+00:00,screenshot_smart,WindowsTerminal,O
6,2026-07-01 16:44:26.054000+00:00,keystroke,WindowsTerminal,idle
7,2026-07-01 16:44:32.083000+00:00,app_switch,Microsoft Edge,idle
8,2026-07-01 16:44:32.183000+00:00,window_state_change,Microsoft Edge,idle
9,2026-07-01 16:44:32.203000+00:00,screenshot_smart,Microsoft Edge,idle
10,2026-07-01 16:44:33.988000+00:00,browser_error,Microsoft Edge,idle
11,2026-07-01 16:44:34.213000+00:00,app_switch,Microsoft Edge,idle
12,2026-07-01 16:44:34.239000+00:00,window_state_change,Microsoft Edge,idle
13,2026-07-01 16:44:34.258000+00:00,app_switch,Microsoft Edge,M
14,2026-07-01 16:44:34.285000+00:00,window_state_change,Microsoft Edge,M

In [48]:
import json

# 1. Create a unique ID for each continuous block of identical processes
df_b['segment_id'] = (df_b['predicted_process'] != df_b['predicted_process'].shift(1)).cumsum()

# 2. Group by these blocks to extract the overall start and end boundaries
segments = []
for _, group in df_b.groupby('segment_id'):
    segments.append({
        "process": group['predicted_process'].iloc[0],
        "start_time": str(group['timestamp_iso'].min()),
        "end_time": str(group['timestamp_iso'].max())
    })

# 3. Export to the required JSONL format
output_file = 'segments.jsonl'
with open(output_file, 'w') as f:
    for seg in segments:
        f.write(json.dumps(seg) + '\n')

print(f"✅ Generated {len(segments)} continuous segments and saved to {output_file}!")

✅ Generated 4916 continuous segments and saved to segments.jsonl!